namespace: argocd

resources:
  - discord-bot.yaml
  - argocd.yaml
  - traefik.yaml
  - pihole.yaml
  - metallb.yaml
  - cert-manager.yaml
  - portainer-agent.yaml
  - external-secrets.yaml
  - portainer.yaml
  - grafana.yaml
  - prometheus.yaml
  - habit-tracker.yaml
  - postgresql.yaml
  - linkwarden.yaml
  - valkey.yaml
  - paperless.yaml
  - plant-tracker.yaml
  - cloudflare-ddns.yaml
